In [23]:
# Import Dependencies and Libraries
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import json
import pprint
import tweepy
import geocoder
import gmaps

# from config_3 import gkey

api_key = "NS0C667Vxg13Pd7WOSVB1w5Hz"
api_key_secret = "vo3ewSknxwmgZSLtGJoIi10XPjoQDBVvii6gNsR3R7nf16ERpJ"
access_token = "24253020-go2gWRKsgW0Zqe0VTBvyT3G2vCrh20taz9oGA5HrJ"
access_token_secret = "UcnEnRboaYAFuLnExdoTAuMopLoBjItNMmLflYdxm1nTP"


# Tweepy
auth = tweepy.OAuthHandler(api_key, api_key_secret)
auth.set_access_token(access_token, access_token_secret)

api = tweepy.API(auth)

public_tweets = api.home_timeline()

In [2]:
# Base url for Collecting 30-Day Endpoint API Data
#https://api.twitter.com/1.1/tweets/search/30day/DataAnalyticsProject.json

from requests_oauthlib import OAuth1

# Get Data About Trending Diet Trends on Twitter: Paleo
url = "https://api.twitter.com/1.1/tweets/search/30day/DataAnalyticsProject.json"
auth = OAuth1(api_key, api_key_secret, access_token, access_token_secret)

url_params = {'query': 'place_country:us #keto'}
r = requests.get(url, auth=auth, params=url_params)

# print(json.dumps(r.json(),indent=4))

In [3]:
# this is an api pull so open a new jupyter notebook window after
# Create Loop Search to assign variable names

# Initialize Variables
keto_location_list = []
keto_location_dict = {}
count = 0

for tweet in r.json()["results"]:
    
    try:
        #Get and print location of tweet
        user_name = tweet["user"]["screen_name"]
        location = tweet["user"]["location"]
        tweet_location = tweet["place"]["full_name"]
        lat, lng = geocoder.arcgis(tweet_location).latlng
        print(f"The user, {user_name}, is located in {tweet_location}, {lat}, {lng}")

        #Build dictionary
        keto_location_dict = {
             "user": user_name,
             "tweet_location": tweet_location,
             "lat": lat,
             "lng": lng
        }

        # Add dictionary to list
        keto_location_list.append(keto_location_dict)
        
        # Increment count
        count = count + 1
    except:
         continue

print(count)


keto_location_df = pd.DataFrame(keto_location_list)
keto_location_df

keto_location_df.to_csv('keto_data_US.csv')

The user, Cheriebomb, is located in Los Olivos, CA, 34.66782000000006, -120.11743999999999
The user, jcflugger, is located in Santa Rosa, CA, 38.43790000000007, -122.71243999999996
The user, Mag3Angels, is located in Fort Collins, CO, 40.581470000000024, -105.07661999999999
The user, farmfresh_prep, is located in San Diego, CA, 32.71568000000008, -117.16170999999997
The user, vickisellsaz, is located in Sahuarita, AZ, 31.957750000000033, -110.96636999999998
The user, hownowbrownpao, is located in Miami, FL, 25.77481000000006, -80.19772999999998
The user, MrsRScott, is located in Independence, MO, 39.09324000000004, -94.41562999999996
The user, xtinalmartin, is located in Indianapolis, IN, 39.76691000000005, -86.14995999999996
The user, Lexow, is located in South Sarasota, FL, 27.28640000000007, -82.53345999999993
The user, livethefuel, is located in Pennsylvania, USA, 40.89651165400005, -77.83875077599998
The user, scottwmulvaney, is located in Allentown, PA, 40.60263000000003, -75.47026999999997
The user, NuttyAboutHlth, is located in San Francisco, CA, 37.777120000000025, -122.41963999999996
The user, bluetsunamilin, is located in Redmond, WA, 47.67858000000007, -122.13157999999999
The user, WeAteThatBlog, is located in Brooklyn, NY, 40.692450000000065, -73.99035999999995
The user, jenringering, is located in Phoenix, AZ, 33.44825000000003, -112.07579999999996
The user, 84_yan_yan, is located in Arizona, USA, 34.29301645100003, -111.66475398799997
The user, CountryCarolyn_, is located in Hendersonville, TN, 36.304860000000076, -86.62020999999999
The user, raybuffer, is located in Torrance, CA, 33.83705000000003, -118.34311999999994
The user, tugar32, is located in Calexico, CA, 32.67864000000003, -115.49866999999995
The user, tugar32, is located in Calexico, CA, 32.67864000000003, -115.49866999999995
The user, 84_yan_yan, is located in Arizona, USA, 34.29301645100003, -111.66475398799997
The user, SueDuffield, is located in Nashville, TN, 36.16784000000007, -86.77815999999996
The user, MarieMyungOkLee, is located in Manhattan, NY, 40.714500000000044, -74.00600999999995
The user, REDHabaneroo, is located in San Francisco, CA, 37.777120000000025, -122.41963999999996
The user, WhereIsJaneMyra, is located in Maplewood, NJ, 40.73115000000007, -74.27691999999996
The user, chelseamhjones, is located in Scottsboro, AL, 34.685200000000066, -86.09460999999999
The user, HayleyCardu, is located in Columbus, OH, 39.96199000000007, -83.00274999999993
The user, FoodieCity, is located in Murrells Inlet, SC, 33.548140000000046, -79.04450999999995
The user, CPACooks, is located in Philadelphia, PA, 39.95222000000007, -75.16217999999998
The user, chelseamhjones, is located in Alabama, USA, 32.766542541000035, -86.84028685899995
The user, Louiegeezy, is located in Burbank, CA, 34.18193000000008, -118.30764999999997
The user, CallMeLeaman, is located in Evansville, IN, 37.97708000000006, -87.56404999999995
The user, Cheriebomb, is located in Los Olivos, CA, 34.66782000000006, -120.11743999999999
The user, mep120183, is located in Schaumburg, IL, 42.026170000000036, -88.06541999999996
The user, HTitusSweany, is located in Los Angeles, CA, 34.05349000000007, -118.24531999999999
The user, chelseamhjones, is located in Alabama, USA, 32.766542541000035, -86.84028685899995
The user, Matman_15, is located in Willowick, OH, 41.63916000000006, -81.47420999999997
The user, DawnEMcKenzie, is located in Wildomar, CA, 33.612360000000024, -117.26236999999998
The user, KellyOC, is located in Long Beach, CA, 33.76672000000008, -118.19239999999996
The user, TheLion61, is located in Ohio, USA, 40.41305679900006, -82.71121518599995
The user, KellyOC, is located in Long Beach, CA, 33.76672000000008, -118.19239999999996
The user, chicadegallo, is located in Boston, MA, 42.35866000000004, -71.05673999999993
The user, HappyGirlsWin, is located in West Virginia, USA, 38.64241493700007, -80.61361664099996
The user, chelseamhjones, is located in Alabama, USA, 32.766542541000035, -86.84028685899995
The user, michaelbpotter, is located in Surprise, AZ, 33.62373000000008, -112.36783999999994
The user, AmberSCallahan, is located in Mount Dora, FL, 28.802490000000034, -81.64451999999994
The user, BigStrongFast, is located in Sacramento, CA, 38.579440000000034, -121.49084999999997
The user, realMacNeil, is located in Landen, OH, 39.31192000000004, -84.28322999999995
The user, shamrock712, is located in New York, USA, 40.71455000000003, -74.00713999999994
The user, GoHeavyDose, is located in Washington, USA, 38.890370000000075, -77.03195999999997
The user, JoyCruzR, is located in Allentown, PA, 40.60263000000003, -75.47026999999997
The user, DanielJuhn, is located in Los Angeles, CA, 34.05349000000007, -118.24531999999999
The user, innocent73, is located in La Habra, CA, 33.93187000000006, -117.94406999999995
The user, johncolucci, is located in KOMO Plaza, 6.022550000000024, 6.912680000000023
The user, jasnev1, is located in Santa Ana, CA, 33.74958000000004, -117.87445999999994
The user, JeremyLarsen82, is located in Sioux Falls, SD, 43.54577000000006, -96.73127999999997
The user, NuttyAboutHlth, is located in Castro Valley, CA, 37.69458000000003, -122.08562999999998
The user, NuttyAboutHlth, is located in Castro Valley, CA, 37.69458000000003, -122.08562999999998
The user, ahorn1674, is located in Pawhuska, OK, 36.663110000000074, -96.33694999999994
The user, Queenkeva75, is located in New York, USA, 40.71455000000003, -74.00713999999994
The user, lndssrn, is located in Brookfield, CT, 41.462090000000046, -73.39624999999995
The user, snarky_ginger1, is located in Mike's Sports Grille, 34.60881998441946, -98.38172997446475
The user, bArtbow, is located in Portsmouth, VA, 36.832730000000026, -76.29770999999994
The user, DawnEMcKenzie, is located in Wildomar, CA, 33.612360000000024, -117.26236999999998
The user, DawnEMcKenzie, is located in Wildomar, CA, 33.612360000000024, -117.26236999999998
The user, LaurieBlackSD, is located in San Diego, CA, 32.71568000000008, -117.16170999999997
The user, NuttyAboutHlth, is located in San Francisco, CA, 37.777120000000025, -122.41963999999996
The user, NuttyAboutHlth, is located in San Francisco, CA, 37.777120000000025, -122.41963999999996
The user, bikinibaconchee, is located in Dallas, TX, 32.77815000000004, -96.79539999999997
The user, bikinibaconchee, is located in Dallas, TX, 32.77815000000004, -96.79539999999997
The user, texasag, is located in Texas, USA, 31.46273304600004, -99.33305008999997
71

In [21]:
keto_location_df.head()

        lat        lng    tweet_location            user
0  34.66782 -120.11744    Los Olivos, CA      Cheriebomb
1  38.43790 -122.71244    Santa Rosa, CA       jcflugger
2  40.58147 -105.07662  Fort Collins, CO      Mag3Angels
3  32.71568 -117.16171     San Diego, CA  farmfresh_prep
4  31.95775 -110.96637     Sahuarita, AZ    vickisellsaz

In [24]:
keto_data_US = pd.read_csv('./keto_data_US.csv')
# keto_data_US_na = keto_data_US_na.dropna()
# keto_data_US_na.head()
keto_data_US

    Unnamed: 0        lat         lng        tweet_location             user
0            0  34.667820 -120.117440        Los Olivos, CA       Cheriebomb
1            1  38.437900 -122.712440        Santa Rosa, CA        jcflugger
2            2  40.581470 -105.076620      Fort Collins, CO       Mag3Angels
3            3  32.715680 -117.161710         San Diego, CA   farmfresh_prep
4            4  31.957750 -110.966370         Sahuarita, AZ     vickisellsaz
5            5  25.774810  -80.197730             Miami, FL   hownowbrownpao
6            6  39.093240  -94.415630      Independence, MO        MrsRScott
7            7  39.766910  -86.149960      Indianapolis, IN     xtinalmartin
8            8  27.286400  -82.533460    South Sarasota, FL            Lexow
9            9  40.896512  -77.838751     Pennsylvania, USA      livethefuel
10          10  40.602630  -75.470270         Allentown, PA   scottwmulvaney
11          11  37.777120 -122.419640     San Francisco, CA   NuttyAboutHlth
12          12  47.678580 -122.131580           Redmond, WA   bluetsunamilin
13          13  40.692450  -73.990360          Brooklyn, NY    WeAteThatBlog
14          14  33.448250 -112.075800           Phoenix, AZ     jenringering
15          15  34.293016 -111.664754          Arizona, USA       84_yan_yan
16          16  36.304860  -86.620210    Hendersonville, TN  CountryCarolyn_
17          17  33.837050 -118.343120          Torrance, CA        raybuffer
18          18  32.678640 -115.498670          Calexico, CA          tugar32
19          19  32.678640 -115.498670          Calexico, CA          tugar32
20          20  34.293016 -111.664754          Arizona, USA       84_yan_yan
21          21  36.167840  -86.778160         Nashville, TN      SueDuffield
22          22  40.714500  -74.006010         Manhattan, NY  MarieMyungOkLee
23          23  37.777120 -122.419640     San Francisco, CA     REDHabaneroo
24          24  40.731150  -74.276920         Maplewood, NJ  WhereIsJaneMyra
25          25  34.685200  -86.094610        Scottsboro, AL   chelseamhjones
26          26  39.961990  -83.002750          Columbus, OH      HayleyCardu
27          27  33.548140  -79.044510    Murrells Inlet, SC       FoodieCity
28          28  39.952220  -75.162180      Philadelphia, PA         CPACooks
29          29  32.766543  -86.840287          Alabama, USA   chelseamhjones
..         ...        ...         ...                   ...              ...
41          41  42.358660  -71.056740            Boston, MA     chicadegallo
42          42  38.642415  -80.613617    West Virginia, USA    HappyGirlsWin
43          43  32.766543  -86.840287          Alabama, USA   chelseamhjones
44          44  33.623730 -112.367840          Surprise, AZ   michaelbpotter
45          45  28.802490  -81.644520        Mount Dora, FL   AmberSCallahan
46          46  38.579440 -121.490850        Sacramento, CA    BigStrongFast
47          47  39.311920  -84.283230            Landen, OH      realMacNeil
48          48  40.714550  -74.007140         New York, USA      shamrock712
49          49  38.890370  -77.031960       Washington, USA      GoHeavyDose
50          50  40.602630  -75.470270         Allentown, PA         JoyCruzR
51          51  34.053490 -118.245320       Los Angeles, CA       DanielJuhn
52          52  33.931870 -117.944070          La Habra, CA       innocent73
53          53   6.022550    6.912680            KOMO Plaza      johncolucci
54          54  33.749580 -117.874460         Santa Ana, CA          jasnev1
55          55  43.545770  -96.731280       Sioux Falls, SD   JeremyLarsen82
56          56  37.694580 -122.085630     Castro Valley, CA   NuttyAboutHlth
57          57  37.694580 -122.085630     Castro Valley, CA   NuttyAboutHlth
58          58  36.663110  -96.336950          Pawhuska, OK        ahorn1674
59          59  40.714550  -74.007140         New York, USA      Queenkeva75
60          60  41.462090  -73.396250        Brookfield, CT          lndssrn
61          61  34.608820  -98.381730  Mike's Sports Grille   snarky_ginger1
62          62  36.832730  -76.297710        Portsmouth, VA          bArtbow
63          63  33.612360 -117.262370          Wildomar, CA    DawnEMcKenzie
64          64  33.612360 -117.262370          Wildomar, CA    DawnEMcKenzie
65          65  32.715680 -117.161710         San Diego, CA    LaurieBlackSD
66          66  37.777120 -122.419640     San Francisco, CA   NuttyAboutHlth
67          67  37.777120 -122.419640     San Francisco, CA   NuttyAboutHlth
68          68  32.778150  -96.795400            Dallas, TX  bikinibaconchee
69          69  32.778150  -96.795400            Dallas, TX  bikinibaconchee
70          70  31.462733  -99.333050            Texas, USA          texasag

[71 rows x 5 columns]

In [25]:
# Add empty City and State columns
keto_data_US['City']=""
keto_data_US['State']=""

In [39]:
# Delimit the values in tweet_location to the two new columns
keto_data_US[["City", "State"]] = keto_data_US["tweet_location"].str.split(",", expand=True)

# Update columns with city and state values as state and USA to blank columns
keto_data_US.iloc[9,5] = ""
keto_data_US.iloc[9,6] = ""
keto_data_US.iloc[15,5] = ""
keto_data_US.iloc[15,6] = ""
keto_data_US.iloc[20,5] = ""
keto_data_US.iloc[20,6] = ""
keto_data_US.iloc[29,5] = ""
keto_data_US.iloc[29,6] = ""
keto_data_US.iloc[35,5] = ""
keto_data_US.iloc[35,6] = ""
keto_data_US.iloc[39,5] = ""
keto_data_US.iloc[39,6] = ""
keto_data_US.iloc[42,5] = ""
keto_data_US.iloc[42,6] = ""
keto_data_US.iloc[43,5] = ""
keto_data_US.iloc[43,6] = ""
keto_data_US.iloc[48,5] = ""
keto_data_US.iloc[48,6] = ""
keto_data_US.iloc[49,5] = ""
keto_data_US.iloc[49,6] = ""
keto_data_US.iloc[59,5] = ""
keto_data_US.iloc[59,6] = ""
keto_data_US.iloc[70,5] = ""
keto_data_US.iloc[70,6] = ""

# Replace all blanks in the state column with correct state
keto_data_US.iloc[9,6] = " PA"
keto_data_US.iloc[15,6] = " AZ"
keto_data_US.iloc[20,6] = " AZ"
keto_data_US.iloc[29,6] = " AL"
keto_data_US.iloc[35,6] = " AL"
keto_data_US.iloc[39,6] = " OH"
keto_data_US.iloc[42,6] = " WV"
keto_data_US.iloc[43,6] = " AL"
keto_data_US.iloc[48,6] = " NY"
keto_data_US.iloc[49,6] = " WA"
keto_data_US.iloc[59,6] = " NY"
keto_data_US.iloc[70,6] = " TX"

keto_data_US_extract = keto_data_US[['lat','lng','tweet_location','user','City','State']]

# Export as CSV
keto_data_US_extract.to_csv('keto_Data_State_Updated.csv')
keto_data_US_extract

,lat,lng,tweet_location,user,City,State
0,34.667820,-120.117440,"Los Olivos, CA",Cheriebomb,Los Olivos,CA
1,38.437900,-122.712440,"Santa Rosa, CA",jcflugger,Santa Rosa,CA
2,40.581470,-105.076620,"Fort Collins, CO",Mag3Angels,Fort Collins,CO
3,32.715680,-117.161710,"San Diego, CA",farmfresh_prep,San Diego,CA
4,31.957750,-110.966370,"Sahuarita, AZ",vickisellsaz,Sahuarita,AZ
5,25.774810,-80.197730,"Miami, FL",hownowbrownpao,Miami,FL
6,39.093240,-94.415630,"Independence, MO",MrsRScott,Independence,MO
7,39.766910,-86.149960,"Indianapolis, IN",xtinalmartin,Indianapolis,IN
8,27.286400,-82.533460,"South Sarasota, FL",Lexow,South Sarasota,FL
9,40.896512,-77.838751,"Pennsylvania, USA",livethefuel,,PA
10,40.602630,-75.470270,"Allentown, PA",scottwmulvaney,Allentown,PA
11,37.777120,-122.419640,"San Francisco, CA",NuttyAboutHlth,San Francisco,CA
12,47.678580,-122.131580,"Redmond, WA",bluetsunamilin,Redmond,WA
13,40.692450,-73.990360,"Brooklyn, NY",WeAteThatBlog,Brooklyn,NY
14,33.448250,-112.075800,"Phoenix, AZ",jenringering,Phoenix,AZ
15,34.293016,-111.664754,"Arizona, USA",84_yan_yan,,AZ
16,36.304860,-86.620210,"Hendersonville, TN",CountryCarolyn_,Hendersonville,TN
17,33.837050,-118.343120,"Torrance, CA",raybuffer,Torrance,CA
18,32.678640,-115.498670,"Calexico, CA",tugar32,Calexico,CA
19,32.678640,-115.498670,"Calexico, CA",tugar32,Calexico,CA
20,34.293016,-111.664754,"Arizona, USA",84_yan_yan,,AZ
21,36.167840,-86.778160,"Nashville, TN",SueDuffield,Nashville,TN
22,40.714500,-74.006010,"Manhattan, NY",MarieMyungOkLee,Manhattan,NY
23,37.777120,-122.419640,"San Francisco, CA",REDHabaneroo,San Francisco,CA
24,40.731150,-74.276920,"Maplewood, NJ",WhereIsJaneMyra,Maplewood,NJ
25,34.685200,-86.094610,"Scottsboro, AL",chelseamhjones,Scottsboro,AL
26,39.961990,-83.002750,"Columbus, OH",HayleyCardu,Columbus,OH
27,33.548140,-79.044510,"Murrells Inlet, SC",FoodieCity,Murrells Inlet,SC
28,39.952220,-75.162180,"Philadelphia, PA",CPACooks,Philadelphia,PA
29,32.766543,-86.840287,"Alabama, USA",chelseamhjones,,AL
...,...,...,...,...,...,...
41,42.358660,-71.056740,"Boston, MA",chicadegallo,Boston,MA
42,38.642415,-80.613617,"West Virginia, USA",HappyGirlsWin,,WV
43,32.766543,-86.840287,"Alabama, USA",chelseamhjones,,AL
44,33.623730,-112.367840,"Surprise, AZ",michaelbpotter,Surprise,AZ
45,28.802490,-81.644520,"Mount Dora, FL",AmberSCallahan,Mount Dora,FL
46,38.579440,-121.490850,"Sacramento, CA",BigStrongFast,Sacramento,CA
47,39.311920,-84.283230,"Landen, OH",realMacNeil,Landen,OH
48,40.714550,-74.007140,"New York, USA",shamrock712,,NY
49,38.890370,-77.031960,"Washington, USA",GoHeavyDose,,WA
50,40.602630,-75.470270,"Allentown, PA",JoyCruzR,Allentown,PA
51,34.053490,-118.245320,"Los Angeles, CA",DanielJuhn,Los Angeles,CA
52,33.931870,-117.944070,"La Habra, CA",innocent73,La Habra,CA
53,6.022550,6.912680,KOMO Plaza,johncolucci,KOMO Plaza,None
54,33.749580,-117.874460,"Santa Ana, CA",jasnev1,Santa Ana,CA
55,43.545770,-96.731280,"Sioux Falls, SD",JeremyLarsen82,Sioux Falls,SD
56,37.694580,-122.085630,"Castro Valley, CA",NuttyAboutHlth,Castro Valley,CA
57,37.694580,-122.085630,"Castro Valley, CA",NuttyAboutHlth,Castro Valley,CA
58,36.663110,-96.336950,"Pawhuska, OK",ahorn1674,Pawhuska,OK
59,40.714550,-74.007140,"New York, USA",Queenkeva75,,NY
60,41.462090,-73.396250,"Brookfield, CT",lndssrn,Brookfield,CT
61,34.608820,-98.381730,Mike's Sports Grille,snarky_ginger1,Mike's Sports Grille,None
62,36.832730,-76.297710,"Portsmouth, VA",bArtbow,Portsmouth,VA
63,33.612360,-117.262370,"Wildomar, CA",DawnEMcKenzie,Wildomar,CA
64,33.612360,-117.262370,"Wildomar, CA",DawnEMcKenzie,Wildomar,CA
65,32.715680,-117.161710,"San Diego, CA",LaurieBlackSD,San Diego,CA
66,37.777120,-122.419640,"San Francisco, CA",NuttyAboutHlth,San Francisco,CA
67,37.777120,-122.419640,"San Francisco, CA",NuttyAboutHlth,San Francisco,CA
68,32.778150,-96.795400,"Dallas, TX",bikinibaconchee,Dallas,TX
69,32.778150,-96.795400,"Dallas, TX",bikinibaconchee,Dallas,TX
70,31.462733,-99.333050,"Texas, USA",texasag,,TX

In [41]:
# Groupby state to get the average lat lng as the location
keto_map_locations = keto_data_US_extract.groupby("State").mean()
keto_map_locations

             lat         lng
State
 AL    33.246207  -86.653868
 AZ    33.523153 -111.747904
 CA    35.032688 -119.229624
 CO    40.581470 -105.076620
 CT    41.462090  -73.396250
 FL    27.287900  -81.458570
 IL    42.026170  -88.065420
 IN    38.871995  -86.857005
 MA    42.358660  -71.056740
 MO    39.093240  -94.415630
 NJ    40.731150  -74.276920
 NY    40.709013  -74.002662
 OH    40.331532  -82.867851
 OK    36.663110  -96.336950
 PA    40.513498  -75.985368
 SC    33.548140  -79.044510
 SD    43.545770  -96.731280
 TN    36.236350  -86.699185
 TX    32.339678  -97.641283
 VA    36.832730  -76.297710
 WA    43.284475  -99.581770
 WV    38.642415  -80.613617

In [42]:
# Count the locations (number of states) and use as weights for heatmap
keto_map_locations_count = keto_data_US["State"].value_counts()
reorg_keto_location_count = keto_map_locations_count.sort_index()
reorg_keto_location_count

 AL     4
 AZ     5
 CA    25
 CO     1
 CT     1
 FL     3
 IL     1
 IN     2
 MA     1
 MO     1
 NJ     1
 NY     4
 OH     4
 OK     1
 PA     4
 SC     1
 SD     1
 TN     2
 TX     3
 VA     1
 WA     2
 WV     1
Name: State, dtype: int64

In [43]:
# Plot heatmap
fig = gmaps.figure()

# Create heat layer
heat_layer = gmaps.heatmap_layer(keto_map_locations, weights=reorg_keto_location_count, dissipating=False, max_intensity=10, point_radius=1)

# Add heat layer
fig.add_layer(heat_layer)
fig

Figure(layout=FigureLayout(height='420px'))